Update AutoLRPT

diff --git a/AutoLRPT b/AutoLRPT
--- a/AutoLRPT
+++ b/AutoLRPT
@@ -21,7 +21,6 @@
         # If you don't want that, set autoflip to 0
         autoflip=1
         
-        
     ## Update color channels automatically
         # Throughout the year, one of Meteor M2's APID channels will switch between
         # 66 and 68. If the color channel isn't updated, the images will often be 
@@ -32,7 +31,6 @@
     
         # Then it will update the channel in mlrpt's config file ~/mlrpt/default.cfg
         upd_channels=1
-        
         
     ## Logging
         # If you want AutoLRPT to log the passes in AutoLRPT.log, set "logging" to 1
@@ -54,164 +52,124 @@ cur_ts=`date +%s`
 # otherways it will wait until the next day.
 [[ $pass_ts -le $cur_ts ]] && sleep 20m
 
+
 # Infinite loop that will always schedule the next pass after the recent one is over
 while true; do
 
-# Automatic update of APID channels
-if [[ $upd_channels -eq 1 ]]; then
+	# Automatic update of APID channels
+	if [[ $upd_channels -eq 1 ]]; then
 
-    # Download the status file if it's not present in AutoLRPT's folder
-    [ -z $(find -name Meteor-M-N2-and-N2-2-Satellite-Operational-Status) ] && git clone https://github.com/happysat/Meteor-M-N2-and-N2-2-Satellite-Operational-Status
+		# Download the status file if it's not present in AutoLRPT's folder
+		[ -z $(find -name Meteor-M-N2-and-N2-2-Satellite-Operational-Status) ] && git clone https://github.com/happysat/Meteor-M-N2-and-N2-2-Satellite-Operational-Status
 
-    # Entering the folder of the status file and updating the file
-    cd Meteor-M-N2-and-N2-2-Satellite-Operational-Status
-    git pull 1>/dev/null
+		# Entering the folder of the status file and updating the file
+		cd Meteor-M-N2-and-N2-2-Satellite-Operational-Status
+		git pull 1>/dev/null
 
-    
-    # Updating the APID channel in mlrpt's config file ~/mlrpt/default.cfg
-    if [[ $(sed '40q;d' README.md) == *"On"* ]]; then
-        sed -i '123s/.*/68/' ~/mlrpt/default.cfg
+		
+		# Updating the APID channel in mlrpt's config file ~/mlrpt/default.cfg
+		if [[ $(sed '40q;d' README.md) == *"On"* ]]; then
+			sed -i '123s/.*/68/' ~/mlrpt/default.cfg
 
-    else
-        sed -i '123s/.*/66/' ~/mlrpt/default.cfg
+		else
+			sed -i '123s/.*/66/' ~/mlrpt/default.cfg
 
-    fi
-    
-    # Return to ~/AutoLRPT
-    cd ..
+		fi
+		
+		# Return to ~/AutoLRPT
+		cd ..
 
-fi
-
-
-
-# Get the UTC time of the upcoming pass from predict
-passtime=`predict '-p' METEOR-M2 | awk '{print $4}' | head -n1`
-
-# Extracting the hour, minute and second of the upcoming pass
-passhour=`cut -c 1-2 <<< $passtime`
-passmin=`cut -c 4-5 <<< $passtime`
-passsec=`cut -c 7-8 <<< $passtime`
-
-# Get the current system hour, minute and second in UTC
-hour=`date --utc +%H`
-min=`date --utc +%M`
-sec=`date --utc +%S`
-
-# Convert the pass time and system time to seconds
-pass_fi=$(( 10#$passhour * 3600 + 10#$passmin * 60 + 10#$passsec ))
-utc_fi=$(( 10#$hour * 3600 + 10#$min * 60 + 10#$sec))
-
-
-# Calculate the difference between the system time and the pass time
-# depending on whether the next pass is on the same day or on the next day.
-if [[ $pass_fi -lt $utc_fi ]]; then
-
-    # In case of the next day
-    utc_fi=$(( 86400 - $utc_fi ))
-    difr=$(( $pass_fi + $utc_fi ))
-
-else
-
-    # In case of the same day
-    difr=$(( $pass_fi - $utc_fi ))
-    
-fi
-
-
-# Making the difference positive
-[ $difr -lt 0 ] && difr=$(( 0 - $difr ))
-
-
-# Getting the elevations of the upcoming pass from predict and parsing them into an array.
-elevs=`predict '-p' METEOR-M2 | awk '{print $5}'`
-readarray -t elev_array <<< $elevs
-
-# Getting the maximum elevation of the upcoming pass.
-IFS=$'\n'
-max_elev=`echo "${elev_array[*]}" | sort -nr | head -n1`
-
-
-# Getting the azimuths of the upcoming pass from predict and extracting the medium azimuth.
-readarray -t azimuth <<< $(predict -p METEOR-M2 | awk '{print $6}')
-azimuth=${azimuth[ $(( ${#azimuth[@]} / 2 )) ]}
-
-
-
-# Wait until the pass begins
-sleep "$difr"s
-
-
-# Variable for the recording success/failure
-    # IMAGE RECORDED    -> If an image was received and saved (successful execution of mlrpt)
-    # NO_IMAGE_RECORDED -> If no image was received (successful execution of mlrpt)
-    # NO_RECORDING      -> If the user disabled the recording (min_elev, evening_rec) under certain circumstances (no execution of mlrpt)
-    # NO_SDR_CONNECTED  -> If mlrpt stops because no SDR was connected
-    # ERROR             -> Any other errors
-rec_status=""
-
-# Variable to save the error code after executing mlrpt
-# 0 -> successful, >0 -> not successful
-success=1
-
-# Minimum elevation check
-if [[ $max_elev -ge $min_elev ]]; then
-    
-    
-    # Check if evening_rec is enabled/disabled and if it's evening.
-    if [[ $evening_rec -eq 1 ]] || [[ 10#$(date +"%H") -le 15 ]]; then
-
-        # Check if Autoflip is enabled and if it's evening
-        if [[ 10#$(date +"%H") -gt 15 ]] && [[ $autoflip -eq 1 ]]; then
-            mlrpt -i > ~/AutoLRPT/mlrpt.log 2>&1
-            success=$?
-
-        else
-            mlrpt > ~/AutoLRPT/mlrpt.log 2>&1
-            success=$?
-
-        fi
-
-    else
-        rec_status="NO_RECORDING"
-    fi
-
-else
-    rec_status="NO_RECORDING"
-fi
-
-# Generating the status
-if [[ $success -eq 0 ]] && [[ $rec_status != "NO_RECORDING" ]]; then
-
-	if [[ -z $(grep "Saving Image" ~/AutoLRPT/mlrpt.log) ]]; then
-		rec_status="NO_IMAGE_RECORDED"
-	else
-		rec_status="IMAGE_RECORDED"
-	fi
-fi
-
-if [[ $success -ne 0 ]] && [[ $rec_status != "NO_RECORDING" ]]; then
-
-	if [[ -z $(grep "Failed to open RTL-SDR device" ~/AutoLRPT/mlrpt.log) ]]; then
-		rec_status="ERROR"
-	else
-		rec_status="NO_SDR_CONNECTED"
 	fi
 
-fi
 
 
+	# Get the UTC time of the upcoming pass from predict
+	passtime=`predict '-p' METEOR-M2 | awk '{print $4}' | head -n1`
 
-# Writing the date, time, maximum elevation, medium azimuth and sucess/error into the log file AutoLRPT.log
-[ $logging -eq 1 ] && echo $(date --utc +%Y-%m-%d) $passhour:$passmin:$passsec $max_elev $azimuth $rec_status >> ~/AutoLRPT/AutoLRPT.log
+	# Calculate the difference between the system time and the pass time
+	difr=$(( $pass_ts - $cur_ts ))
 
-
-# Moving the images to the webserver's image folder
-# The webserver's image folder (in the case below /var/www/html/images) must have writing permissions for that!
-#[[ -z $(ls ~/mlrpt/images) ]] && mv ~/mlrpt/images/* /var/www/html/images
-
-
-# Wait for 20 minutes until the next pass is being scheduled
-# (This will ensure that the next pass will be scheduled although no SDR has been connected)
-sleep 20m
-
+	# Getting the elevations of the upcoming pass from predict and parsing them into an array.
+	elevs=`predict '-p' METEOR-M2 | awk '{print $5}'`
+	readarray -t elev_array <<< $elevs
+	
+	# Getting the maximum elevation of the upcoming pass.
+	IFS=$'\n'
+	max_elev=`echo "${elev_array[*]}" | sort -nr | head -n1`
+	
+	# Getting the azimuths of the upcoming pass from predict and extracting the medium azimuth.
+	readarray -t azimuth <<< $(predict -p METEOR-M2 | awk '{print $6}')
+	azimuth=${azimuth[ $(( ${#azimuth[@]} / 2 )) ]}
+	
+	
+	# Wait until the pass begins
+	sleep "$difr"s
+	
+	
+	# Variable for the recording success/failure
+		# IMAGE RECORDED    -> If an image was received and saved (successful execution of mlrpt)
+		# NO_IMAGE_RECORDED -> If no image was received (successful execution of mlrpt)
+		# NO_RECORDING      -> If the user disabled the recording (min_elev, evening_rec) under certain circumstances (no execution of mlrpt)
+		# NO_SDR_CONNECTED  -> If mlrpt stops because no SDR was connected
+		# ERROR             -> Any other errors
+	rec_status=""
+	
+	# Variable to save the error code after executing mlrpt
+	# 0 -> successful, >0 -> not successful
+	success=1
+	
+	
+	# Minimum elevation check
+	if [[ $max_elev -ge $min_elev ]]; then
+		
+		# Check if evening_rec is enabled/disabled and if it's evening.
+		if [[ $evening_rec -eq 1 ]] || [[ 10#$(date +"%H") -le 15 ]]; then
+			
+			# Check if Autoflip is enabled and if it's evening
+			if [[ 10#$(date +"%H") -gt 15 ]] && [[ $autoflip -eq 1 ]]; then
+				mlrpt -i > ~/AutoLRPT/mlrpt.log 2>&1
+				success=$?
+			else
+				mlrpt > ~/AutoLRPT/mlrpt.log 2>&1
+				success=$?
+			fi
+		else
+			rec_status="NO_RECORDING"
+		fi
+	else
+		rec_status="NO_RECORDING"
+	fi
+	
+	
+	# Generating the status
+	if [[ $success -eq 0 ]] && [[ $rec_status != "NO_RECORDING" ]]; then
+		if [[ -z $(grep "Saving Image" ~/AutoLRPT/mlrpt.log) ]]; then
+			rec_status="NO_IMAGE_RECORDED"
+		else
+			rec_status="IMAGE_RECORDED"
+		fi
+	fi
+	
+	if [[ $success -ne 0 ]] && [[ $rec_status != "NO_RECORDING" ]]; then
+		if [[ -z $(grep "Failed to open RTL-SDR device" ~/AutoLRPT/mlrpt.log) ]]; then
+			rec_status="ERROR"
+		else
+			rec_status="NO_SDR_CONNECTED"
+		fi
+	fi
+	
+	
+	# Writing the date, time, maximum elevation, medium azimuth and sucess/error into the log file AutoLRPT.log
+	[ $logging -eq 1 ] && echo $(date --utc +%Y-%m-%d) $passtime $max_elev $azimuth $rec_status >> ~/AutoLRPT/AutoLRPT.log
+	
+	
+	# Moving the images to the webserver's image folder
+	# The webserver's image folder (in the case below /var/www/html/images) must have writing permissions for that!
+	#[[ -z $(ls ~/mlrpt/images) ]] && mv ~/mlrpt/images/* /var/www/html/images
+	
+	
+	# Wait for 20 minutes until the next pass is being scheduled
+	# (This will ensure that the next pass will be scheduled although no SDR has been connected)
+	sleep 20m
+	
 done
